version: "3.8"
services:
  database:
    image: postgres
    network_mode: host
    container_name: database
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    network_mode: host
    # ports:
    #   - 3333:3333
    volumes:
      - .:/app

volumes:
  pgdata: